name: .NET Core Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish HeatingDaemon/HeatingMqttService/HeatingMqttService.csproj -c Release -r linux-arm --self-contained false /p:PublishSingleFile=true /p:DebugType=none

    - name: Rename to example.appsettings.json
      run: mv ./HeatingDaemon/HeatingMqttService/bin/Release/net10.0/linux-arm/publish/appsettings.json ./HeatingDaemon/HeatingMqttService/bin/Release/net10.0/linux-arm/publish/example.appsettings.json
    - name: Generate an zip file
      run: zip --junk-paths HeatingMqttService-linux-arm ./HeatingDaemon/HeatingMqttService/bin/Release/net10.0/linux-arm/publish/*
    - name: List published files
      run: ls -R ./HeatingDaemon/HeatingMqttService/bin/Release/net10.0/linux-arm/publish/

    - name: Check if Release exists
      id: check_release
      run: |
        if gh release view latest > /dev/null 2>&1; then echo "exists=true" >> $GITHUB_ENV; else echo "exists=false" >> $GITHUB_ENV; fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Delete Release if it exists
      if: env.exists == 'true'
      run: gh release delete latest --cleanup-tag --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release latest
        draft: false
        prerelease: true

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./HeatingMqttService-linux-arm.zip   
        asset_name: HeatingMqttService-linux-arm.zip
        asset_content_type: application/zip
